version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=journal
  backend:
    build:
      context: ./journal-backend
      dockerfile: Dockerfile
    image: strapi-pm2:latest
    ports:
      - "1337:1337"
    env_file:
      - journal-backend/.env
    depends_on:
      - postgres
    
  frontend:
    build:
      context: ./journal-frontend
    volumes:
      - app_build:/journal/dist
  nginx:
    image: nginx:latest
    ports:
      - 8081:80
      - "4443:443"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - app_build:/var/www/journal
    depends_on:
      - frontend
      - backend
  
volumes:
  app_build:
  postgres_data:
